"use client";
import { useQuery } from "@tanstack/react-query";
import { X } from "lucide-react";
import { getFormAnalytics } from "../../lib/api/analytics";
import { queryKeys } from "../../lib/query-keys";
import { Button } from "../ui/Button";
import { formatDate } from "../../lib/utils";

interface AnalyticsPanelProps {
  formId: string;
  onClose: () => void;
}

export function AnalyticsPanel({ formId, onClose }: AnalyticsPanelProps) {
  const { data: snapshots = [], isLoading } = useQuery({
    queryKey: queryKeys.analytics.snapshots(formId, 30),
    queryFn: () => getFormAnalytics(formId, 30),
  });

  const latest = snapshots[0];

  return (
    <div className="border-b border-[var(--border-default)] bg-[var(--bg-elevated)] px-4 py-4">
      <div className="mb-3 flex items-center justify-between">
        <div>
          <h2 className="text-sm font-semibold text-[var(--text-primary)]">Analytics</h2>
          <p className="text-xs text-[var(--text-tertiary)]">
            Daily snapshots generated by Inngest.
          </p>
        </div>
        <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close analytics">
          <X className="h-4 w-4" />
        </Button>
      </div>

      {isLoading ? (
        <p className="text-sm text-[var(--text-tertiary)]">Loading analytics...</p>
      ) : !latest ? (
        <p className="text-sm text-[var(--text-tertiary)]">No analytics snapshots yet.</p>
      ) : (
        <div className="grid gap-3 sm:grid-cols-4">
          <Metric label="Total" value={latest.totalSubmissions} />
          <Metric label="Anonymous" value={latest.anonymousSubmissions} />
          <Metric label="Sponsored" value={latest.sponsoredSubmissions} />
          <Metric label="Self-paid" value={latest.selfPaidSubmissions} />
          <p className="sm:col-span-4 text-xs text-[var(--text-tertiary)]">
            Last snapshot: {formatDate(latest.periodStart)}
          </p>
        </div>
      )}
    </div>
  );
}

function Metric({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-subtle)] p-3">
      <p className="text-xs text-[var(--text-tertiary)]">{label}</p>
      <p className="mt-1 text-lg font-semibold text-[var(--text-primary)]">{value}</p>
    </div>
  );
}
